sonar.exclusions=e2e/**,**/*.spec.ts,**/*.test.jsx,**/*.test.js,src/test/**
sonar.cpd.exclusions=e2e/**,**/*.spec.ts,**/*.test.jsx,**/*.test.js,src/test/**
sonar.test.inclusions=e2e/**,**/*.spec.ts,**/*.test.jsx,**/*.test.js,src/test/**
