sonar.sources=src
sonar.tests=src
sonar.exclusions=e2e/**,**/e2e/**,**/*.spec.ts,**/*.test.jsx,**/*.test.js,src/**/__tests__/**,src/test/**,coverage/**,**/*.local-backup.*
sonar.cpd.exclusions=e2e/**,**/e2e/**,e2e/group-email.spec.ts,e2e/group-transfer.spec.ts,**/*.spec.ts,**/*.test.jsx,**/*.test.js,src/**/__tests__/**,src/test/**,coverage/**,**/*.local-backup.*
sonar.test.inclusions=src/**/__tests__/**,src/test/**,**/*.test.jsx,**/*.test.js
