sonar.projectKey=peerconnect-frontend
sonar.projectName=PeerConnect Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js
sonar.exclusions=src/**/*.test.jsx,src/**/*.test.js,src/test/**,coverage/**,dist/**,node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
